author: xHexed
name: LeaderMobs
main: com.github.xhexed.leadermobs.LeaderMobs
version: ${project.version}
api-version: "1.13"
softdepend: [Boss, MythicMobs]
commands:
  lm:
    usage: /lm
    aliases: [leadermobs]
permissions:
  lm.reload:
    default: op
  lm.toggle:
    default: op